### ISSUE TITLE
angular2 rc.5

### ISSUE THREAD

**Issue by amarewgs** [nkalinov/ng2-datetime#37]
stops working with the latest angular2 rc.5, 'No value accessor for form control with unspecified name'. was working well on the previous versions

**Comment by ciesielskico** [comment]
You need to add a 'name' attribute, like this: 
`<datetime name="datepicker" #datepicker="ngModel" (ngModelChange)="handleDatepickerChange($event)" [ngModel]="model.transactionDate" [datepicker]="datepickerOptions" [timepicker]="timepickerOptions"></datetime>`

**Comment by nkalinov** [comment]
Hi @ciesielskico,
I haven't tested yed, is this everything to "make it work" ?
If yes, I will close the issue.
Thanks!

**Comment by ciesielskico** [comment]
@nkalinov adding the name attribute is enough to solve the error mentioned above since I got the same one when moving from RC3 to RC4, specifically using the new forms module. 
However,  now I'm having a "No provider for ngControl" error, after migrating to RC5 and the newly introduced modules. I'm not yet sure if it's my fault with importing the forms module in a wrong way or if your component needs an update.  
Will investigate later today.

**Comment by amarewgs** [comment]
yeah I have done everything to migrate it to rc5 and all other things work but can't make it work for a custom control like the datetime picker. check this http://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-component

**Comment by shadeeka** [comment]
did anyone able to use this component with angular-rc5.

**Comment by oscarpr** [comment]
Uncaught No Directive annotation found on NKDatetime. when i upgrate to RC5

**Comment by stephanjust** [comment]
It works just fine for me using RC5 (using "ng2-datetime": "1.1.4"), so getting into more details with your errors might help.

**Comment by chocapic54** [comment]
Unfortunately, it seems that ng2-datetime (1.1.3 1.1.4 and 1.1.5) doesn't works with @angular/forms 0.3.0,
But 1.1.3 and 1.1.4 works with forms 0.2.0 (not 1.1.5)

**Comment by ciesielskico** [comment]
Getting the same issue with Angular RC5, Form 0.3.0 and angular-cli@webpack

`Uncaught No Directive annotation found on NKDatetime`

I'm investigating if this is an issue related to the new NgModules, will update later.

**Comment by sidewaiise** [comment]
Resolved this by adding `<datepicker .... [formControl]="form.controls['mycontrol']">...`, however now I'm getting `TypeError: $(...).timepicker is not a function` from `NKDateTime.init`
